name: list_todos_module
description: "A new Flutter module project."


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.list.todos.list_todos_module
    iosBundleIdentifier: com.example.list.todos.listTodosModule
