name: flutter_module
description: "A new Flutter module project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  add_todo_module:
    path: ./modules/add_todo_module  
  edit_todo_module:
    path: ./modules/edit_todo_module
  list_todos_module:
    path: ./modules/list_todos_module
  collection: 1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
